# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
- repo: self
queue:
  name: Hosted VS2017
steps:
- task: ArchiveFiles@2
  displayName: 'Archive Extension'
  inputs:
    rootFolderOrFile: Extension

    includeRootFolder: false

    archiveFile: '$(Build.ArtifactStagingDirectory)/EpicUserWebSearch.zip'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    Contents: ChromeWebStoreBashScript.sh

    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'



