name: build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    outputs:
      version_commit: ${{ steps.output-version-commit.outputs.version_commit }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12'
        if: ${{ github.ref_protected == 0}} #don't install node if we aren't bumping version

      - name: bump version
        uses: michmich112/version-bumper@319a22fd31a212eb26cfb33c40fffa37c6a0c099 # 1.2.0
        with:
          options-file: ./.github/version-bumper-options.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.ref_protected == 0}} #don't bump version on protected branches since we can't

      - name: create extension.zip
        uses: TheDoctor0/zip-release@4fb9e4ff72847dd3d1c111cf63834e353ed7cb3d  # 0.6.0
        with:
          type: zip
          filename: EpicUserWebSearch.zip
          path: Extension

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: EpicUserWebSearch
          path: EpicUserWebSearch.zip

      - id: output-version-commit
        name: output-version-commit
        run: |
          VERSION_COMMIT=$(git rev-parse HEAD)
          echo $VERSION_COMMIT
          echo "::set-output name=version_commit::$VERSION_COMMIT"
  
  deploy-to-chrome: #create a second job so secrets aren't potentially exposed to third-party code
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: EpicUserWebSearch
          path: ./
      
      - name: upload to chrome webstore test extension
        uses: markiannucci/chrome-extension-upload-action@main
        with: 
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          app-id: kckhgocjclanicadmlgaapcgohmcaikc
          file-name: EpicUserWebSearch.zip
          publish: true
          publish-target: trustedTesters
        if: ${{ github.ref != 'refs/heads/main' }}

      # https://github.community/t/github-actions-as-status-checks/16666/16
      - name: Create status check ver bumped version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
          GITHUB_WORKFLOW: ${{ env.GITHUB_WORKFLOW }}
          BUILD_COMMIT: ${{ needs.build.outputs.version_commit }}
        run: |
          curl \
          -X POST \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/$GITHUB_REPOSITORY/check-runs \
          -d '{"name":"'"$GITHUB_WORKFLOW"'", "head_sha": "'"$BUILD_COMMIT"'", "status": "completed", "conclusion": "success" }'
        if: ${{ github.ref_protected == 0}} #only pass github the completed status check when we bump the version

      - name: upload to chrome webstore real extension
        uses: markiannucci/chrome-extension-upload-action@main
        with: 
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          app-id: ginlmldponabcjidalfoboonnmloeolj
          file-name: EpicUserWebSearch.zip
          publish: true
          publish-target: default
        if: ${{ github.ref == 'refs/heads/main'}}

      - name: upload json files
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: WebstoreJsonOutput
          path: '*.json'