name: build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: create extension.zip
        uses: TheDoctor0/zip-release@0.6.0
        with:
          type: zip
          filename: EpicUserWebSearch.zip
          path: Extension

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: EpicUserWebSearch
          path: EpicUserWebSearch.zip

      - name: upload to chrome webstore test extension
        uses: Passiverecords/chrome-extension-upload-action@1.4.1
        with: 
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          app-id: kckhgocjclanicadmlgaapcgohmcaikc
          file-name: EpicUserWebSearch.zip
          publish: true